Added volunteer type and count value
akashtakyar/covidindiahelp-web pull request #15
Opened 2021-05-31 05:40 UTC by ChaudharyShiva18

2021-05-31 11:14 UTC, ayushkul requested changes

2021-05-31 11:14 UTC, ayushkul commented on src/services/columns.js
> +  let url = `https://www.covidindiahelp.info:3002/count`;
Connect with API gateway

2021-05-31 11:35 UTC, ChaudharyShiva18 commented on src/services/columns.js
> +  let url = `https://www.covidindiahelp.info:3002/count`;
Done

2021-06-03 07:05 UTC, lhtdeepaktomar commented on src/modules/leadDetails/index.js
> +  };
why removed this function?

2021-06-03 07:05 UTC, lhtdeepaktomar commented on src/modules/leadDetails/index.js
> -        this.handleWorkingPopoverClose();
why removed this function also

2021-06-03 07:11 UTC, merged